In [14]:
import pandas as pd
import numpy as np
from pandasql import sqldf
import pandasql
import statistics
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3

In [16]:
football = pd.read_csv('2015 FootballData.csv')
football

C:\Users\homer\AppData\Local\Temp\ipykernel_13816\1740109962.py:1: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  football = pd.read_csv('2015 FootballData.csv')

,Unnamed: 0,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,...,Accepted.Penalty,PenalizedTeam,PenaltyType,PenalizedPlayer,Penalty.Yards,PosTeamScore,DefTeamScore,ScoreDiff,AbsScoreDiff,Season
0,36,9/10/2015,2015091000,1,1,NaN,15:00,15,3600.0,0.0,...,0,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,2015
1,51,9/10/2015,2015091000,1,1,1.0,15:00,15,3600.0,0.0,...,0,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,2015
2,72,9/10/2015,2015091000,1,1,1.0,14:21,15,3561.0,39.0,...,0,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,2015
3,101,9/10/2015,2015091000,1,1,2.0,14:04,15,3544.0,17.0,...,0,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,2015
4,122,9/10/2015,2015091000,1,1,1.0,13:26,14,3506.0,38.0,...,0,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46124,389412,1/3/2016,2016010310,22,4,4.0,0:43,1,43.0,7.0,...,0,NaN,NaN,NaN,0,13.0,19.0,-6.0,6.0,2015
46125,391814,1/3/2016,2016010310,22,4,1.0,0:27,1,27.0,16.0,...,0,NaN,NaN,NaN,0,13.0,19.0,-6.0,6.0,2015
46126,394216,1/3/2016,2016010310,22,4,2.0,0:24,1,24.0,3.0,...,0,NaN,NaN,NaN,0,13.0,19.0,-6.0,6.0,2015
46127,396414,1/3/2016,2016010310,22,4,3.0,0:15,1,15.0,9.0,...,0,NaN,NaN,NaN,0,13.0,19.0,-6.0,6.0,2015
46128,39949,1/3/2016,2016010310,22,4,4.0,0:01,1,1.0,14.0,...,0,NaN,NaN,NaN,0,13.0,19.0,-6.0,6.0,2015

In [17]:
#Just checking first 15 rows to make sure data is correctly brought over to python
football.head(15)

,Unnamed: 0,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,...,Accepted.Penalty,PenalizedTeam,PenaltyType,PenalizedPlayer,Penalty.Yards,PosTeamScore,DefTeamScore,ScoreDiff,AbsScoreDiff,Season
0,36,9/10/2015,2015091000,1,1,NaN,15:00,15,3600.0,0.0,...,0,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,2015
1,51,9/10/2015,2015091000,1,1,1.0,15:00,15,3600.0,0.0,...,0,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,2015
2,72,9/10/2015,2015091000,1,1,1.0,14:21,15,3561.0,39.0,...,0,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,2015
3,101,9/10/2015,2015091000,1,1,2.0,14:04,15,3544.0,17.0,...,0,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,2015
4,122,9/10/2015,2015091000,1,1,1.0,13:26,14,3506.0,38.0,...,0,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,2015
5,159,9/10/2015,2015091000,1,1,1.0,12:42,13,3462.0,44.0,...,0,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,2015
6,180,9/10/2015,2015091000,1,1,1.0,12:05,13,3425.0,37.0,...,0,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,2015
7,199,9/10/2015,2015091000,1,1,2.0,11:20,12,3380.0,45.0,...,1,PIT,NaN,M.Gilbert,10,0.0,0.0,0.0,0.0,2015
8,236,9/10/2015,2015091000,1,1,2.0,10:53,11,3353.0,27.0,...,0,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,2015
9,261,9/10/2015,2015091000,1,1,3.0,10:28,11,3328.0,25.0,...,0,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,2015
10,285,9/10/2015,2015091000,1,1,4.0,9:44,10,3284.0,44.0,...,0,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,2015
11,305,9/10/2015,2015091000,2,1,1.0,9:40,10,3280.0,4.0,...,1,NE,NaN,N.Solder,15,0.0,0.0,0.0,0.0,2015
12,346,9/10/2015,2015091000,2,1,1.0,9:14,10,3254.0,26.0,...,0,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,2015
13,371,9/10/2015,2015091000,2,1,1.0,9:00,9,3240.0,14.0,...,0,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,2015
14,396,9/10/2015,2015091000,2,1,1.0,8:31,9,3211.0,29.0,...,0,NaN,NaN,NaN,0,0.0,0.0,0.0,0.0,2015

In [18]:
#Checking data types
football.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46129 entries, 0 to 46128
Data columns (total 66 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          46129 non-null  int64
 1   Date                46129 non-null  object
 2   GameID              46129 non-null  int64
 3   Drive               46129 non-null  int64
 4   qtr                 46129 non-null  int64
 5   down                39006 non-null  float64
 6   time                46102 non-null  object
 7   TimeUnder           46129 non-null  int64
 8   TimeSecs            46102 non-null  float64
 9   PlayTimeDiff        46075 non-null  float64
 10  SideofField         46063 non-null  object
 11  yrdln               46021 non-null  float64
 12  yrdline100          46021 non-null  float64
 13  ydstogo             46129 non-null  int64
 14  ydsnet              46129 non-null  int64
 15  GoalToGo            46021 non-null  float64
 16  FirstDown           42811 non-null  float64
 17  posteam             42878 non-null  object
 18  DefensiveTeam       42878 non-null  object
 19  desc                46129 non-null  object
 20  PlayAttempted       46129 non-null  int64
 21  Yards.Gained        46129 non-null  int64
 22  sp                  46129 non-null  int64
 23  Touchdown           46129 non-null  int64
 24  ExPointResult       1131 non-null   object
 25  TwoPointConv        89 non-null     object
 26  DefTwoPoint         5 non-null      object
 27  Safety              46129 non-null  int64
 28  PuntResult          2485 non-null   object
 29  PlayType            46129 non-null  object
 30  Passer              19398 non-null  object
 31  PassAttempt         46129 non-null  int64
 32  PassOutcome         19435 non-null  object
 33  PassLength          19291 non-null  object
 34  PassLocation        19291 non-null  object
 35  InterceptionThrown  46129 non-null  int64
 36  Interceptor         467 non-null    object
 37  Rusher              13066 non-null  object
 38  RushAttempt         46129 non-null  int64
 39  RunLocation         12966 non-null  object
 40  RunGap              9587 non-null   object
 41  Receiver            18458 non-null  object
 42  Reception           46129 non-null  int64
 43  ReturnResult        2344 non-null   object
 44  Returner            2498 non-null   object
 45  BlockingPlayer      11 non-null     object
 46  Tackler1            24903 non-null  object
 47  Tackler2            3356 non-null   object
 48  FieldGoalResult     1001 non-null   object
 49  FieldGoalDistance   989 non-null    float64
 50  Fumble              46129 non-null  int64
 51  RecFumbTeam         481 non-null    object
 52  RecFumbPlayer       481 non-null    object
 53  Sack                46129 non-null  int64
 54  Challenge.Replay    46129 non-null  int64
 55  ChalReplayResult    413 non-null    object
 56  Accepted.Penalty    46129 non-null  int64
 57  PenalizedTeam       3535 non-null   object
 58  PenaltyType         1952 non-null   object
 59  PenalizedPlayer     3404 non-null   object
 60  Penalty.Yards       46129 non-null  int64
 61  PosTeamScore        42878 non-null  float64
 62  DefTeamScore        42878 non-null  float64
 63  ScoreDiff           42878 non-null  float64
 64  AbsScoreDiff        42878 non-null  float64
 65  Season              46129 non-null  int64
dtypes: float64(12), int64(22), object(32)
memory usage: 23.2+ MB

In [19]:
#Checking rows
len(football)

46129

In [20]:
#Checking Columns
football.columns.size

66

In [21]:
#Finding Nulls
football.notnull()

,Unnamed: 0,Date,GameID,Drive,qtr,down,time,TimeUnder,TimeSecs,PlayTimeDiff,...,Accepted.Penalty,PenalizedTeam,PenaltyType,PenalizedPlayer,Penalty.Yards,PosTeamScore,DefTeamScore,ScoreDiff,AbsScoreDiff,Season
0,True,True,True,True,True,False,True,True,True,True,...,True,False,False,False,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,False,False,False,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,False,False,False,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,False,False,False,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,False,False,False,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46124,True,True,True,True,True,True,True,True,True,True,...,True,False,False,False,True,True,True,True,True,True
46125,True,True,True,True,True,True,True,True,True,True,...,True,False,False,False,True,True,True,True,True,True
46126,True,True,True,True,True,True,True,True,True,True,...,True,False,False,False,True,True,True,True,True,True
46127,True,True,True,True,True,True,True,True,True,True,...,True,False,False,False,True,True,True,True,True,True
46128,True,True,True,True,True,True,True,True,True,True,...,True,False,False,False,True,True,True,True,True,True

In [22]:
#Groupby passing leaders
football.groupby(by='Passer')['Yards.Gained'].sum()

Passer
A.Andrews           41
A.Dalton          3436
A.Davis            578
A.Luck            2049
A.McCarron         889
                  ...
T.Jackson           37
T.Romo             914
T.Taylor          3206
T.Yates            373
Z.Mettenberger     984
Name: Yards.Gained, Length: 86, dtype: int64

In [3]:
#bringing in nfl play by play package
pip install nfl_data_py --user

Collecting nfl_data_py
  Using cached nfl_data_py-0.3.0-py3-none-any.whl
Requirement already satisfied: pandas>1 in c:\users\homer\anaconda3\lib\site-packages (from nfl_data_py) (2.0.0)
Requirement already satisfied: python-snappy>0.5 in c:\users\homer\anaconda3\lib\site-packages (from nfl_data_py) (0.6.0)
Collecting fastparquet>0.5
  Using cached fastparquet-2023.2.0-cp39-cp39-win_amd64.whl (619 kB)
Requirement already satisfied: appdirs>1 in c:\users\homer\anaconda3\lib\site-packages (from nfl_data_py) (1.4.4)
Requirement already satisfied: fsspec in c:\users\homer\anaconda3\lib\site-packages (from fastparquet>0.5->nfl_data_py) (2022.7.1)
Requirement already satisfied: numpy>=1.20.3 in c:\users\homer\anaconda3\lib\site-packages (from fastparquet>0.5->nfl_data_py) (1.21.5)
Requirement already satisfied: cramjam>=2.3 in c:\users\homer\anaconda3\lib\site-packages (from fastparquet>0.5->nfl_data_py) (2.6.2)
Requirement already satisfied: packaging in c:\users\homer\anaconda3\lib\site-packages (from fastparquet>0.5->nfl_data_py) (21.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\homer\anaconda3\lib\site-packages (from pandas>1->nfl_data_py) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in c:\users\homer\anaconda3\lib\site-packages (from pandas>1->nfl_data_py) (2023.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\homer\anaconda3\lib\site-packages (from pandas>1->nfl_data_py) (2022.1)
Requirement already satisfied: six>=1.5 in c:\users\homer\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>1->nfl_data_py) (1.16.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\homer\anaconda3\lib\site-packages (from packaging->fastparquet>0.5->nfl_data_py) (3.0.9)
Installing collected packages: fastparquet, nfl_data_py
Successfully installed fastparquet-2023.2.0 nfl_data_py-0.3.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import nfl_data_py as nfl

In [29]:
years = [2019, 2020, 2021, 2022]

In [6]:
nfl.see_pbp_cols()

Index(['play_id', 'game_id', 'old_game_id', 'home_team', 'away_team',
       'season_type', 'week', 'posteam', 'posteam_type', 'defteam',
       ...
       'out_of_bounds', 'home_opening_kickoff', 'qb_epa', 'xyac_epa',
       'xyac_mean_yardage', 'xyac_median_yardage', 'xyac_success', 'xyac_fd',
       'xpass', 'pass_oe'],
      dtype='object', length=372)

In [30]:
#df = nfl.import_pbp_data
df = nfl.import_pbp_data(years)

2019 done.
2020 done.
2021 done.
2022 done.
Downcasting floats.

In [31]:
#all the column names
list(df.columns)

['play_id',
 'game_id',
 'old_game_id',
 'home_team',
 'away_team',
 'season_type',
 'week',
 'posteam',
 'posteam_type',
 'defteam',
 'side_of_field',
 'yardline_100',
 'game_date',
 'quarter_seconds_remaining',
 'half_seconds_remaining',
 'game_seconds_remaining',
 'game_half',
 'quarter_end',
 'drive',
 'sp',
 'qtr',
 'down',
 'goal_to_go',
 'time',
 'yrdln',
 'ydstogo',
 'ydsnet',
 'desc',
 'play_type',
 'yards_gained',
 'shotgun',
 'no_huddle',
 'qb_dropback',
 'qb_kneel',
 'qb_spike',
 'qb_scramble',
 'pass_length',
 'pass_location',
 'air_yards',
 'yards_after_catch',
 'run_location',
 'run_gap',
 'field_goal_result',
 'kick_distance',
 'extra_point_result',
 'two_point_conv_result',
 'home_timeouts_remaining',
 'away_timeouts_remaining',
 'timeout',
 'timeout_team',
 'td_team',
 'td_player_name',
 'td_player_id',
 'posteam_timeouts_remaining',
 'defteam_timeouts_remaining',
 'total_home_score',
 'total_away_score',
 'posteam_score',
 'defteam_score',
 'score_differential',
 'posteam_score_post',
 'defteam_score_post',
 'score_differential_post',
 'no_score_prob',
 'opp_fg_prob',
 'opp_safety_prob',
 'opp_td_prob',
 'fg_prob',
 'safety_prob',
 'td_prob',
 'extra_point_prob',
 'two_point_conversion_prob',
 'ep',
 'epa',
 'total_home_epa',
 'total_away_epa',
 'total_home_rush_epa',
 'total_away_rush_epa',
 'total_home_pass_epa',
 'total_away_pass_epa',
 'air_epa',
 'yac_epa',
 'comp_air_epa',
 'comp_yac_epa',
 'total_home_comp_air_epa',
 'total_away_comp_air_epa',
 'total_home_comp_yac_epa',
 'total_away_comp_yac_epa',
 'total_home_raw_air_epa',
 'total_away_raw_air_epa',
 'total_home_raw_yac_epa',
 'total_away_raw_yac_epa',
 'wp',
 'def_wp',
 'home_wp',
 'away_wp',
 'wpa',
 'vegas_wpa',
 'vegas_home_wpa',
 'home_wp_post',
 'away_wp_post',
 'vegas_wp',
 'vegas_home_wp',
 'total_home_rush_wpa',
 'total_away_rush_wpa',
 'total_home_pass_wpa',
 'total_away_pass_wpa',
 'air_wpa',
 'yac_wpa',
 'comp_air_wpa',
 'comp_yac_wpa',
 'total_home_comp_air_wpa',
 'total_away_comp_air_wpa',
 'total_home_comp_yac_wpa',
 'total_away_comp_yac_wpa',
 'total_home_raw_air_wpa',
 'total_away_raw_air_wpa',
 'total_home_raw_yac_wpa',
 'total_away_raw_yac_wpa',
 'punt_blocked',
 'first_down_rush',
 'first_down_pass',
 'first_down_penalty',
 'third_down_converted',
 'third_down_failed',
 'fourth_down_converted',
 'fourth_down_failed',
 'incomplete_pass',
 'touchback',
 'interception',
 'punt_inside_twenty',
 'punt_in_endzone',
 'punt_out_of_bounds',
 'punt_downed',
 'punt_fair_catch',
 'kickoff_inside_twenty',
 'kickoff_in_endzone',
 'kickoff_out_of_bounds',
 'kickoff_downed',
 'kickoff_fair_catch',
 'fumble_forced',
 'fumble_not_forced',
 'fumble_out_of_bounds',
 'solo_tackle',
 'safety',
 'penalty',
 'tackled_for_loss',
 'fumble_lost',
 'own_kickoff_recovery',
 'own_kickoff_recovery_td',
 'qb_hit',
 'rush_attempt',
 'pass_attempt',
 'sack',
 'touchdown',
 'pass_touchdown',
 'rush_touchdown',
 'return_touchdown',
 'extra_point_attempt',
 'two_point_attempt',
 'field_goal_attempt',
 'kickoff_attempt',
 'punt_attempt',
 'fumble',
 'complete_pass',
 'assist_tackle',
 'lateral_reception',
 'lateral_rush',
 'lateral_return',
 'lateral_recovery',
 'passer_player_id',
 'passer_player_name',
 'passing_yards',
 'receiver_player_id',
 'receiver_player_name',
 'receiving_yards',
 'rusher_player_id',
 'rusher_player_name',
 'rushing_yards',
 'lateral_receiver_player_id',
 'lateral_receiver_player_name',
 'lateral_receiving_yards',
 'lateral_rusher_player_id',
 'lateral_rusher_player_name',
 'lateral_rushing_yards',
 'lateral_sack_player_id',
 'lateral_sack_player_name',
 'interception_player_id',
 'interception_player_name',
 'lateral_interception_player_id',
 'lateral_interception_player_name',
 'punt_returner_player_id',
 'punt_returner_player_name',
 'lateral_punt_returner_player_id',
 'lateral_punt_returner_player_name',
 'kickoff_returner_player_name',
 'kickoff_returner_player_id',
 'lateral_kickoff_returner_player_id',
 'lateral_kickoff_returner_player_name',
 'punter_player_id',
 'punter_player_name',
 'kicker_player_name',
 'kicker_player_id',
 'own_kickoff_recovery_player_id',
 'own_kickoff_recovery_player_name',
 'blocked_player_id',
 'blocked_player_name',
 'tackle_for_loss_1_player_id',
 'tackle_for_loss_1_player_name',
 'tackle_for_loss_2_player_id',
 'tackle_for_loss_2_player_name',
 'qb_hit_1_player_id',
 'qb_hit_1_player_name',
 'qb_hit_2_player_id',
 'qb_hit_2_player_name',
 'forced_fumble_player_1_team',
 'forced_fumble_player_1_player_id',
 'forced_fumble_player_1_player_name',
 'forced_fumble_player_2_team',
 'forced_fumble_player_2_player_id',
 'forced_fumble_player_2_player_name',
 'solo_tackle_1_team',
 'solo_tackle_2_team',
 'solo_tackle_1_player_id',
 'solo_tackle_2_player_id',
 'solo_tackle_1_player_name',
 'solo_tackle_2_player_name',
 'assist_tackle_1_player_id',
 'assist_tackle_1_player_name',
 'assist_tackle_1_team',
 'assist_tackle_2_player_id',
 'assist_tackle_2_player_name',
 'assist_tackle_2_team',
 'assist_tackle_3_player_id',
 'assist_tackle_3_player_name',
 'assist_tackle_3_team',
 'assist_tackle_4_player_id',
 'assist_tackle_4_player_name',
 'assist_tackle_4_team',
 'tackle_with_assist',
 'tackle_with_assist_1_player_id',
 'tackle_with_assist_1_player_name',
 'tackle_with_assist_1_team',
 'tackle_with_assist_2_player_id',
 'tackle_with_assist_2_player_name',
 'tackle_with_assist_2_team',
 'pass_defense_1_player_id',
 'pass_defense_1_player_name',
 'pass_defense_2_player_id',
 'pass_defense_2_player_name',
 'fumbled_1_team',
 'fumbled_1_player_id',
 'fumbled_1_player_name',
 'fumbled_2_player_id',
 'fumbled_2_player_name',
 'fumbled_2_team',
 'fumble_recovery_1_team',
 'fumble_recovery_1_yards',
 'fumble_recovery_1_player_id',
 'fumble_recovery_1_player_name',
 'fumble_recovery_2_team',
 'fumble_recovery_2_yards',
 'fumble_recovery_2_player_id',
 'fumble_recovery_2_player_name',
 'sack_player_id',
 'sack_player_name',
 'half_sack_1_player_id',
 'half_sack_1_player_name',
 'half_sack_2_player_id',
 'half_sack_2_player_name',
 'return_team',
 'return_yards',
 'penalty_team',
 'penalty_player_id',
 'penalty_player_name',
 'penalty_yards',
 'replay_or_challenge',
 'replay_or_challenge_result',
 'penalty_type',
 'defensive_two_point_attempt',
 'defensive_two_point_conv',
 'defensive_extra_point_attempt',
 'defensive_extra_point_conv',
 'safety_player_name',
 'safety_player_id',
 'season',
 'cp',
 'cpoe',
 'series',
 'series_success',
 'series_result',
 'order_sequence',
 'start_time',
 'time_of_day',
 'stadium',
 'weather',
 'nfl_api_id',
 'play_clock',
 'play_deleted',
 'play_type_nfl',
 'special_teams_play',
 'st_play_type',
 'end_clock_time',
 'end_yard_line',
 'fixed_drive',
 'fixed_drive_result',
 'drive_real_start_time',
 'drive_play_count',
 'drive_time_of_possession',
 'drive_first_downs',
 'drive_inside20',
 'drive_ended_with_score',
 'drive_quarter_start',
 'drive_quarter_end',
 'drive_yards_penalized',
 'drive_start_transition',
 'drive_end_transition',
 'drive_game_clock_start',
 'drive_game_clock_end',
 'drive_start_yard_line',
 'drive_end_yard_line',
 'drive_play_id_started',
 'drive_play_id_ended',
 'away_score',
 'home_score',
 'location',
 'result',
 'total',
 'spread_line',
 'total_line',
 'div_game',
 'roof',
 'surface',
 'temp',
 'wind',
 'home_coach',
 'away_coach',
 'stadium_id',
 'game_stadium',
 'aborted_play',
 'success',
 'passer',
 'passer_jersey_number',
 'rusher',
 'rusher_jersey_number',
 'receiver',
 'receiver_jersey_number',
 'pass',
 'rush',
 'first_down',
 'special',
 'play',
 'passer_id',
 'rusher_id',
 'receiver_id',
 'name',
 'jersey_number',
 'id',
 'fantasy_player_name',
 'fantasy_player_id',
 'fantasy',
 'fantasy_id',
 'out_of_bounds',
 'home_opening_kickoff',
 'qb_epa',
 'xyac_epa',
 'xyac_mean_yardage',
 'xyac_median_yardage',
 'xyac_success',
 'xyac_fd',
 'xpass',
 'pass_oe',
 'nflverse_game_id',
 'possession_team',
 'offense_formation',
 'offense_personnel',
 'defenders_in_box',
 'defense_personnel',
 'number_of_pass_rushers',
 'players_on_play',
 'offense_players',
 'defense_players',
 'n_offense',
 'n_defense']

In [37]:
df = nfl.import_pbp_data(years, downcast=True, cache=False, alt_path=None)

2019 done.
2020 done.
2021 done.
2022 done.
Downcasting floats.

In [54]:
#calling specific columns from dataframe
football_update = df[[
 'game_id',
 'home_team',
 'away_team',
 'week',
 'posteam',
 'defteam',
 'side_of_field',
 'yardline_100',
 'game_date',
 'qtr',
 'down',
 'time',
 'yrdln',
 'ydstogo',
 'desc',
 'play_type',
 'yards_gained',
 'qb_scramble',
 'pass_length',
 'pass_location',
 'air_yards',
 'yards_after_catch',
 'run_location',
 'run_gap',
 'field_goal_result',
 'kick_distance',
 'td_team',
 'td_player_name',
 'total_home_score',
 'total_away_score',
 'posteam_score',
 'defteam_score',
 'score_differential',
 'score_differential_post',
 'incomplete_pass',
 'interception',
 'solo_tackle',
 'safety',
 'penalty',
 'tackled_for_loss',
 'rush_attempt',
 'pass_attempt',
 'sack',
 'touchdown',
 'pass_touchdown',
 'rush_touchdown',
 'return_touchdown',
 'extra_point_attempt',
 'two_point_attempt',
 'field_goal_attempt',
 'kickoff_attempt',
 'punt_attempt',
 'fumble',
 'complete_pass',
 'passer_player_name',
 'passing_yards',
 'receiver_player_id',
 'receiving_yards',
 'rusher_player_id',
 'rusher_player_name',
 'rushing_yards',
 'interception_player_name',
 'tackle_for_loss_1_player_name',
 'solo_tackle_1_player_name',
 'sack_player_name',
 'return_team',
 'return_yards',
 'penalty_team',
 'penalty_player_name',
 'penalty_yards',
 'penalty_type',
 'series',
 'series_success',
 'series_result',
 'stadium',
 'weather',
 'play_type_nfl',
 'end_clock_time',
 'end_yard_line',
 'away_score',
 'home_score',
 'location',
 'total',
 'spread_line',
 'total_line',
 'temp',
 'wind',
]]

football_update

,game_id,home_team,away_team,week,posteam,defteam,side_of_field,yardline_100,game_date,qtr,...,end_clock_time,end_yard_line,away_score,home_score,location,total,spread_line,total_line,temp,wind
0,2019_01_ATL_MIN,MIN,ATL,1,None,None,None,NaN,2019-09-08,1.0,...,None,None,12,28,Home,40,3.5,47.0,NaN,NaN
1,2019_01_ATL_MIN,MIN,ATL,1,ATL,MIN,MIN,35.0,2019-09-08,1.0,...,None,ATL 25,12,28,Home,40,3.5,47.0,NaN,NaN
2,2019_01_ATL_MIN,MIN,ATL,1,ATL,MIN,ATL,75.0,2019-09-08,1.0,...,None,ATL 17,12,28,Home,40,3.5,47.0,NaN,NaN
3,2019_01_ATL_MIN,MIN,ATL,1,ATL,MIN,ATL,83.0,2019-09-08,1.0,...,None,ATL 21,12,28,Home,40,3.5,47.0,NaN,NaN
4,2019_01_ATL_MIN,MIN,ATL,1,ATL,MIN,ATL,79.0,2019-09-08,1.0,...,None,ATL 33,12,28,Home,40,3.5,47.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197402,2022_22_KC_PHI,PHI,KC,22,None,None,None,NaN,2023-02-12,4.0,...,None,None,38,35,Neutral,73,1.0,51.0,NaN,NaN
197403,2022_22_KC_PHI,PHI,KC,22,KC,PHI,PHI,9.0,2023-02-12,4.0,...,00:08,None,38,35,Neutral,73,1.0,51.0,NaN,NaN
197404,2022_22_KC_PHI,PHI,KC,22,PHI,KC,KC,35.0,2023-02-12,4.0,...,00:07,PHI 36,38,35,Neutral,73,1.0,51.0,NaN,NaN
197405,2022_22_KC_PHI,PHI,KC,22,PHI,KC,PHI,64.0,2023-02-12,4.0,...,00:00,PHI 36,38,35,Neutral,73,1.0,51.0,NaN,NaN
197406,2022_22_KC_PHI,PHI,KC,22,None,None,None,NaN,2023-02-12,4.0,...,None,None,38,35,Neutral,73,1.0,51.0,NaN,NaN

In [56]:
football_receiver = df[[
 'receiver_player_id',
 'receiver_player_name'
]]
football_receiver

       receiver_player_id receiver_player_name
0                    None                 None
1                    None                 None
2                    None                 None
3                    None                 None
4                    None                 None
...                   ...                  ...
197402               None                 None
197403               None                 None
197404               None                 None
197405               None                 None
197406               None                 None

[197407 rows x 2 columns]

In [59]:
football_td = df[[
 'td_player_id',
 'fantasy_player_name'
]]
football_td

       td_player_id fantasy_player_name
0              None                None
1              None                None
2              None                None
3              None           D.Freeman
4              None              M.Ryan
...             ...                 ...
197402         None                None
197403         None                None
197404         None                None
197405         None                None
197406         None                None

[197407 rows x 2 columns]

In [57]:
football_receiver.to_csv('receiver.csv')

In [52]:
football_update.to_csv('Football_update.csv')

In [38]:
df['play_id']

0            1.0
1           36.0
2           51.0
3           79.0
4          100.0
           ...
197402    4035.0
197403    4024.0
197404    4050.0
197405    4072.0
197406    4094.0
Name: play_id, Length: 197407, dtype: float64

In [40]:
#checking unique values of pass location
df.pass_location.unique()

array([None, 'left', 'middle', 'right'], dtype=object)